### ISSUE TITLE
Log config "start" parameter named confusingly.

### ISSUE THREAD

**Issue by pgporada** [letsencrypt/ct-woodpecker#108]
Am I correct in assuming that the `logs` config parameter `start` is the per log version of `inclusionConfig.startIndex`? What I am seeing is contrary to my assumption though and I need some clarification. Here's my logs snippet
```
...
  "logs": [
    {
      "uri": "https://testflume.ct.letsencrypt.org/2019"
     ,"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAg3+vFOesFW51rKECekioAt9Zo50atRoOJ0qLxF7DIEHsHneXLEpgO1WMreleRy1vEbUJD7TXoH9r8qSDGvyew=="
     ,"submitPreCert": true
     ,"submitCert": true
     ,"windowStart": "2019-01-01T00:00:00Z"
     ,"windowEnd": "2020-01-01T00:00:00Z"
     ,"start": 666000000
    },
    {
      "uri": "https://testflume.ct.letsencrypt.org/2020"
     ,"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjdjcoKpeBShHgHvRm3BxD5+l+eHZudv3KmD5SDcLcI01Vj5TDTmxanQKCgpvm9pfnfB6URMQV3hhU1I02jRoRw=="
     ,"submitPreCert": true
     ,"submitCert": true
     ,"windowStart": "2020-01-01T00:00:00Z"
     ,"windowEnd": "2021-01-01T00:00:00Z"
     ,"start": 1
    },
    {
      "uri": "https://testflume.ct.letsencrypt.org/2021"
     ,"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdCLoJNt1QcNa7sNDp7g7oTJ+o/UIYEM6N/IZWT+dhdqtJZC+AODJ/4exdOwG04B4K6WrN1VB2ELKQIc/wU1lCw=="
     ,"submitPreCert": true
     ,"submitCert": true
     ,"windowStart": "2021-01-01T00:00:00Z"
     ,"windowEnd": "2022-01-01T00:00:00Z"
     ,"start": 1
    },
    {
      "uri": "https://testflume.ct.letsencrypt.org/2022"
     ,"key": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjy/rXcABuf0yhrm1+XgjDnh4XPD7vfMoyJOyT+KA+c2zuXVR98yQmp/Bl5ZFdGFwJuFcVrCw7IDo0EGKs7UCww=="
     ,"submitPreCert": true
     ,"submitCert": true
     ,"windowStart": "2022-01-01T00:00:00Z"
     ,"windowEnd": "2023-01-01T00:00:00Z"
     ,"start": 1
    },
  ]
...
```

Here is the output I'm getting from that ct-woodpecker instance. Upon restart of the ct-woodpecker process I would expect the inclusionChecker to begin requesting entries from the `start` parameter per log.
```
2019/11/05 01:55:01 inclusionChecker https://testflume.ct.letsencrypt.org/2019 : current matches tree size. There are no new entries to check for inclusion.
2019/11/05 01:55:01 inclusionChecker https://testflume.ct.letsencrypt.org/2021 : current matches tree size. There are no new entries to check for inclusion.
2019/11/05 01:55:01 inclusionChecker https://testflume.ct.letsencrypt.org/2020 : Getting entries from 83367535 to 83367631
2019/11/05 01:55:01 inclusionChecker https://testflume.ct.letsencrypt.org/2022 : current matches tree size. There are no new entries to check for inclusion.
```

**Comment by pgporada** [comment]
Aha! The `logs[].start` option is used by the database to keep track of its last known searched position. If that `logs[].start` is configured less than what the database has, the config option is unused which seems counter-intuitive.

**Comment by jsha** [comment]
Yep! The idea is that if you are bringing ct-woodpecker online for the first time against a big log (or if you've dropped the database, for instance), you don't necessarily want it to iterate through all the past entries before it gets down to business. We could probably rename this field to something like min-entry. Do you think that would clarify? We should probably also update the godoc at https://godoc.org/github.com/letsencrypt/ct-woodpecker/woodpecker#LogConfig, which currently just says "// TreeSize to start at when checking for inclusion".

**Comment by pgporada** [comment]
I think that renaming it to `min-entry` would help to clarify it. Thanks!

**Comment by cpu** [comment]
> I think that renaming it to min-entry would help to clarify it. Thanks!

@jsha @pgporada PTAL: https://github.com/letsencrypt/ct-woodpecker/pull/109
