### ISSUE TITLE
Periodically submit certificates from a special-purpose root

### ISSUE THREAD

**Issue by jsha** [letsencrypt/ct-woodpecker#2]
To test that a log is accepting submissions, ct-woodpecker should accept a private key and root certificate, with which it can sign new certificates once a minute or so and submit them to the log. This would be a special-purpose root, not trusted by any software except the CT log under test.

ct-woodpecker should export latency and error stats from these submissions, and count it as an error if the SCT fails to verify.

**Comment by jsha** [comment]
BTW, we should probably default this root and the signed certificates to ECDSA (P-256) to minimize size.

**Comment by cpu** [comment]
My implementation for this focuses on submitting final certificates to a log, not precertificates. We might want to consider doing both in the future as a follow-up issue.
