### ISSUE TITLE
Submit duplicate certificates and precertificates

### ISSUE THREAD

**Issue by jsha** [letsencrypt/ct-woodpecker#5]
To catch conditions like this non-incorporation of SCTs for duplicate certificates: https://groups.google.com/a/chromium.org/forum/#!topic/ct-policy/E88pjOZzkIM

**Comment by cpu** [comment]
We talked about this in a call yesterday: it's simple to have the `certSubmitter` submit duplicates of its own precerts/certs. We should do that as a matter of diligence but outside of this issue. It would be more interesting to use this issue to track submitting copies of certificates from observed from calls to `get-entries` on the CT server.

**Comment by jsha** [comment]
Note: This can be done by choosing a random index smaller than the tree size, fetching it, then re-submitting it.

**Comment by cpu** [comment]
> it's simple to have the certSubmitter submit duplicates of its own precerts/certs. We should do that as a matter of diligence but outside of this issue.

Tracking that in https://github.com/letsencrypt/ct-woodpecker/issues/54
