### ISSUE TITLE
Handle stale STHs

### ISSUE THREAD

**Issue by jsha** [letsencrypt/ct-woodpecker#61]
Some logs have caching frontends and we may see STHs slightly out-of-order. We should handle this gracefully.

**Comment by cpu** [comment]
Initially this will mean only overwriting the prevSTH when the newSTH has treesize >= the prevSTH. If the newSTH has a treesize < the prevSTH and the newSTH's timestamp is outside of the MMD an error stat should be incremented and a warning/err message printed.
