### ISSUE TITLE
Investigate possible memory leak

### ISSUE THREAD

**Issue by jsha** [letsencrypt/ct-woodpecker#98]

**Comment by cpu** [comment]
Related: https://github.com/letsencrypt/ct-woodpecker/issues/81

**Comment by cpu** [comment]
I ran a few configurations of `ct-woodpecker` locally for ~4hrs, collecting heap profiles using the `pprof` supported added in #81.

The `ct-woodpecker` process virtual memory was stable throughout with no significant deviations. Similarly the heap profiles collected didn't have anything that pointed towards a leak. The inclusion checker is the largest user of memory (mostly by way of `scan`ing certificate bytes from `sql.Rows` into `SubmittedCert.Cert` `[]byte` fields, which involves a `copy`) but the memory consumed isn't being leaked as best I can tell.

Similarly the graph of memory usage from the production `ct-woodpecker` instance doesn't indicate to me that there is a leak. I'd normally expect to see some kind of saw-toothing pattern or some visible trend in upward memory usage over time and neither are present:

![30d mem usage](https://user-images.githubusercontent.com/292650/56366760-d6b0bc80-61c1-11e9-9cf8-b6e88e603c48.png)

On April 8th SRE changed the inclusion checker config's `maxGetEntries` from `5000` to `3000` and that seems to have stabilized the memory usage in the graph shown above (but again doesn't suggest there was a leak). The box only has 2GB of memory shared between `ct-woodpecker` and the MariaDB instance. I suspect its just oversubscribed and would benefit from more RAM.

I'm going to close this issue with that recommendation.
